name: Android Build

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Updated to match your local Flutter version
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true

      - name: Verify Flutter Installation
        run: flutter doctor

      - name: Get Dependencies
        run: flutter pub get

      # Removed the Flutter Tests step

      - name: Build APK
        run: flutter build apk --release

      # Replace the current upload approach with the direct artifact upload
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
